import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


import "./globals_boot.css"
import "bootstrap-icons/font/bootstrap-icons.css"



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'todo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/todo-icon.png" type="image/icon type" />
      </head>
      <body className={`${inter.className} font-sans-serif`}>{children}</body>
    </html>
  )
}
